### PR TITLE
Upgrade kotlin version to 2.0.20

### PR DESCRIPTION
**Pull request by pauljoug**
When trying to use wifi_flutter in a project that uses a recent kotlin versions it is needed to upgrade the kotlin version of wifi_flutter.

### CODE REVIEW

**Comment by pauljoug** [comment]
@vipero07 is there any downside to upgrade the kotlin version of this project?
Thanks a lot

**Comment by vipero07** [comment]
Not to my knowledge, I'll merge this.

**Review by vipero07 — APPROVED** [review]

**Comment by vipero07** [comment]
Gimme a bit to push an update to pub. I should look into automating that.

**Comment by pauljoug** [comment]
@vipero07 did you find the time to update to pub?
Thanks a lot

**Comment by pauljoug** [comment]
@vipero07 May I bother you again with the update of this plugin? Thanks a lot!

**Pull request merged**
