### PR TITLE
Upgrade plugin: support android embeddings 2, compileSdkVersion 31

### PR DESCRIPTION
**Pull request by pauljoug**
The intent of this PR is to make `wifi_flutter` plugin compatible with Android 2 embeddings.
It is also updated to a more recent SDK version.

It seems to me that the test I removed never worked as I do not see any mention of PlatformVersion in the code.

Thanks @vipero07 if you can take a look at it.

### CODE REVIEW

**Comment by pauljoug** [comment]
@vipero07 I am not sure I can add you as a reviewer or assign you. Would you mind taking a look at it? Thank you very much!

**Review by vipero07 — APPROVED** [review]

**Comment by vipero07** [comment]
I'm going to have to make a release but not sure when I'll have the time. I'll try and get it out in the next 24hr

**Comment by pauljoug** [comment]
Great! Is it going to appear as version 0.2.0 there? https://pub.dev/packages/wifi_flutter/versions

**Comment by vipero07** [comment]
It will, yes, sorry been a bit distracted.

**Comment by pauljoug** [comment]
Hi @vipero07 I see now that the plugin is flagged as dart 3 incompatible on the pubdev webpage. I am hoping this release might fix that. Did you have time to trigger it? Thanks!

**Comment by pauljoug** [comment]
Hi @vipero07, I wonder if I could help for the release. Thanks again for your time!

**Comment by vipero07** [comment]
https://pub.dev/packages/wifi_flutter/changelog done, sorry for the wait.

**Comment by vipero07** [comment]
I made a minor change, instead of it returning a possibly null it just returns an empty iterable, so no need to check for nulls.

**Comment by pauljoug** [comment]
Thanks!

**Pull request merged**
